# Generated by Django 3.1.3 on 2022-05-26 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20220525_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='grade',
            new_name='points',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='title',
        ),
        migrations.AddField(
            model_name='choice',
            name='content',
            field=models.CharField(default='choice content', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='content',
            field=models.CharField(default='question content', max_length=50),
        ),
    ]
