# Generated by Django 3.1.3 on 2022-05-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_auto_20220526_0136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='points',
            new_name='grade',
        ),
        migrations.RemoveField(
            model_name='question',
            name='lesson',
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(default='question title', max_length=550),
        ),
    ]
