# Generated by Django 3.1.3 on 2022-05-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0005_auto_20220526_0450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='grade',
            new_name='points',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='title',
        ),
        migrations.AddField(
            model_name='choice',
            name='content',
            field=models.CharField(default='question text', max_length=99),
        ),
        migrations.AddField(
            model_name='question',
            name='content',
            field=models.CharField(default='question title', max_length=99),
        ),
    ]
