# Generated by Django 3.1.3 on 2022-05-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0007_auto_20220526_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='title',
        ),
        migrations.AddField(
            model_name='choice',
            name='content',
            field=models.CharField(default='choice content', max_length=550),
        ),
        migrations.AddField(
            model_name='question',
            name='content',
            field=models.CharField(default='question content', max_length=550),
        ),
    ]
