# Generated by Django 3.1.3 on 2022-05-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0008_auto_20220526_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='content',
            field=models.CharField(default='choice content', max_length=99),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.CharField(default='question content', max_length=99),
        ),
    ]
